[package]
name = "do-kube-config-updater"
version = "0.0.1"
authors = ["Mike Engel <mike@mike-engel.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
reqwest = "0.9"
log = "0.4"
simplelog = "0.5"
dirs = "1"
